apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
#      - ./infra/k8s-dev/*
build:
  local:
    push: false
  artifacts:
    - image: pristinewebdev/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: pristinewebdev/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
        - src: '**/*.ts'
          dest: .
    - image: pristinewebdev/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
        - src: 'src/**/*.ts'
          dest: .
#    - image: pristinewebdev/orders
#      context: orders
#      docker:
#        dockerfile: Dockerfile
#      sync:
#        manual:
#        - src: 'src/**/*.ts'
#          dest: .
#    - image: pristinewebdev/expiration
#      context: expiration
#      docker:
#        dockerfile: Dockerfile
#      sync:
#        manual:
#        - src: 'src/**/*.ts'
#          dest: .
#    - image: pristinewebdev/payments
#      context: payments
#      docker:
#        dockerfile: Dockerfile
#      sync:
#        manual:
#        - src: 'src/**/*.ts'
#          dest: .
