apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: iceshop/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: iceshop/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
        - src: '**/*.js'
          dest: .
    - image: iceshop/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
        - src: 'src/**/*.ts'
          dest: .
    - image: iceshop/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
        - src: 'src/**/*.ts'
          dest: .
    - image: iceshop/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
        - src: 'src/**/*.ts'
          dest: .
