apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: pristine-app-com-tls
spec:
  secretName: pristine-app-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: pristine-app.com
  dnsNames:
    - pristine-app.com
    - www.pristine-app.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - pristine-app.com
          - www.pristine-app.com
